myapp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy
from django.views.static import serve

from myapp import views
from django.conf import settings
from django.contrib.auth import views as auth_views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    # What is r in Django?
    # This is a prefix for raw strings (escape sequences are ignored) which is useful for sane regular expressions.
    # Excerpt from the docs: When an r' or R' prefix is present,
    # backslashes are still used to quote the following character,
    # but all backslashes are left in the string.
    path('about/', views.about, name='about'),
    path('<int:cat_no>/', views.detail, name='cat_no'),
    path('products/', views.products, name='products'),
    path('place_order/', views.place_order, name='place_order'),
    path('<int:prod_id>', views.productdetail, name='prod_id'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('myorders/', views.myorders, name='myorders'),
    path('register/', views.user_register, name='register'),
    path('upload_photo/', views.upload_photo, name='upload_photo'),
    path('display_profile/', views.display_profile, name = 'display_profile'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='myapp/password_reset.html'),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='myapp/password_reset_sent.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='myapp/password_reset_done.html'),
         name='password_reset_complete')
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

mysiteF21/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),

    path('myapp/', include('django.contrib.auth.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.
from django.db import models
import datetime
from django.contrib.auth.models import User
from django import forms
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=200, blank=False, default='Windsor')

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100, validators=[MaxValueValidator(1000), MinValueValidator(0)])
    available = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    interested = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def refill(self):
        return self.stock + 100


class Client(User):
    PROVINCE_CHOICES = [('AB', 'Alberta'),
                        ('MB', 'Manitoba'),
                        ('ON', 'Ontario'),
                        ('QC', 'Quebec'), ]
    company = models.CharField(max_length=50, blank=True)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)
    photo = models.ImageField(blank=True, null=True,upload_to="photo/")

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def get_absolute_url(self):
        return reverse("myapp:index", kwargs={"id": self.id})

    def get_interested(self):
        return ",".join([str(i) for i in self.interested_in.all()])


class Order(models.Model):
    ORDER_CHOICES = [(0, 'Order Cancelled'),
                     (1, 'Order Placed'),
                     (2, 'Order Shipped'),
                     (3, 'Order Delivered'), ]
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField(default=1)
    order_status = models.IntegerField(choices=ORDER_CHOICES, default=1)
    status_date = models.DateField(default="2021-10-17")

    def __str__(self):
        return self.product.name

    def total_cost(self):
        return self.product.price * self.num_units

class Photo(models.Model):
	name = models.CharField(max_length=50)
	profile_Main_Img = models.ImageField(blank=True, null=True,upload_to="photo/")

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from myapp.models import Order, Product, Client, Photo


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['client', 'product', 'num_units']
        widgets = {
            'client': forms.RadioSelect
        }
        labels = {
            'num_units': 'Quantity',
            'client': 'Client Name'
        }


# class InterestForm2(forms.ModelForm):
#     CHOICES = [
#         (1, 'YES'),
#         (0, 'NO')
#     ]
#     interested = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
#     quantity = forms.IntegerField(initial=1)
#     comment = forms.CharField(widget=forms.Textarea, required=False, label='Additional Comment')
#
#     class Meta:
#         model = Product
#         fields = ['interested']


class InterestForm(forms.Form):
    CHOICES = [
        (1, 'YES'),
        (0, 'NO')
    ]
    interested = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    quantity = forms.IntegerField(initial=1)
    comment = forms.CharField(widget=forms.Textarea, required=False, label='Additional Comment')


class RegisterForm(UserCreationForm):
    class Meta:
        model = Client
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class UploadPhoto(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['photo']

myapp/views.py
# Create your views here.
# Import necessary classes
import datetime

from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import OrderForm, InterestForm, RegisterForm, UploadPhoto
from .models import Category, Product, Client, Order, Photo
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test


# Create your views here.
def index(request):
    cat_list = Category.objects.all().order_by('id')[:10]
    msg = ''
    last_login = ''
    if 'last_login' not in request.session:
        msg = 'Your last login was more than one hour ago'
    else:
        last_login = 'Last login time is ' + request.session.get('last_login')
    return render(request, 'myapp/index.html', {'cat_list': cat_list,
                                                'msg': msg,
                                                'last_login': last_login})


def about(request):
    about_visits = request.session.get('about_visits', 0)
    request.session['about_visits'] = about_visits + 1
    request.session.set_expiry(300)
    return render(request, 'myapp/about.html', {'about_visits': about_visits})


def detail(request, cat_no):
    # category = Category.objects.get(id=cat_no)
    category = get_object_or_404(Category, id=cat_no)
    warehouse = category.warehouse
    product_list = Product.objects.filter(category=cat_no)

    return render(request, 'myapp/detail.html',
                  {'category': category,
                   'warehouse': warehouse,
                   'product_list': product_list})


def products(request):
    prodlist = Product.objects.all().order_by('id')[:50]
    return render(request, 'myapp/products.html', {'prodlist': prodlist})


def place_order(request):
    msg = ''
    prodlist = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_units <= order.product.stock:
                order.product.stock = order.product.stock - order.num_units
                if order.product.stock == 0:
                    order.product.available = False
                order.product.save()
                order.save()
                msg = 'Your order has been placed successfully.'
            else:
                msg = 'We do not have sufficient stock to fill your order.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prodlist': prodlist})


def productdetail(request, prod_id):
    # prod = Product.objects.get(id=prod_id)
    prod = get_object_or_404(Product, pk=prod_id)
    prodname = prod.name
    prodprice = prod.price
    prodinterested = prod.interested
    prodavailable = prod.available

    if request.method == 'POST':
        form = InterestForm(request.POST)
        print('post')
        if form.is_valid():
            print('valid')
            interested = form.cleaned_data['interested']
            # https://docs.djangoproject.com/en/3.2/ref/forms/api/
            if interested == 1:
                prod.interested += 1
                prod.save(update_fields=['interested'])
                return render(request, 'myapp/index.html')
            else:
                return render(request, 'myapp/productsdetail.html')
    else:
        form = InterestForm()
        print('not post')
    return render(request, 'myapp/productsdetail.html', {'form': form,
                                                         'prod': prod,
                                                         'prodname': prodname,
                                                         'prodprice': prodprice,
                                                         'prodinterested': prodinterested,
                                                         'prodavailable': prodavailable})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                last_login = datetime.datetime.now().strftime('%c')
                request.session['last_login'] = str(last_login)
                request.session.set_expiry(3600)
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


def user_register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
        return redirect("myapp:index")
    else:
        form = RegisterForm()

    return render(response, 'myapp/register.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


@login_required(login_url='/myapp/login/')
def myorders(request):
    username = request.user.username

    if Client.objects.get(username__contains=username):
        try:
            order_product = Order.objects.filter(client__first_name__contains=username)
        except:
            return HttpResponse('You did not order anything')
    else:
        return HttpResponse('You are not a registered client!')
    return render(request, 'myapp/myorders.html', {'username': username,
                                                   'order_product': order_product})
def upload_photo(request):
    username = request.user.username
    instance = get_object_or_404(Client, username=username)
    if request.method == 'POST':
        form = UploadPhoto(request.POST, request.FILES,instance=instance)

        if form.is_valid():
            instance = form.save()
            instance.save()
            return redirect('myapp:display_profile')
    else:
        form = UploadPhoto()
    return render(request, 'myapp/upload_photo.html', {'form': form})



def display_profile(request):
    if request.method == 'GET':
        # getting all the objects of hotel.
        username = request.user.username
        print(username)
        instance = get_object_or_404(Client, username=username)
        return render(request, 'myapp/display_profile_images.html',{'profile_images': instance})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block myhdg %}Hello {{ username }} {% endblock %}
{% block body_block %}
    <p>This is an Online Store APP</p>
    <p>you have visited {{ about_visits }} times</p>
{#    <p><a href="/myapp/">Index Page(hardcoded url)</a></p>#}
{#    <p><a href="{% url 'myapp:index' %}">Index Page(url namespacing)</a></p>#}
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>
    <p>This is an Online Store APP</p>
    <p><a href="/myapp/">Index Page(hardcoded url)</a></p>
    <p><a href="{% url 'myapp:index' %}">Index Page(url namespacing)</a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
        <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>
         <div>
            {% if user.is_authenticated %}
                <a href="{% url 'myapp:myorders' %}">Myorders</a>
                <br>
                <form action="{% url 'myapp:logout' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Logout" />
                </form>
            {% else %}
                <a href="{% url 'myapp:login' %}">Login</a>
                <br>
                <a href="{% url 'myapp:register' %}">Register Here</a>
            {% endif %}
        </div>
        <div>
            <h1>
                {% with username=request.user.username %}
                {% block myhdg %}Hello {{ username }} {% endblock %}</h1>
                {% endwith %}
                {% block body_block %} *** {% endblock %}
        </div>

        <hr />
        <div>
            <ul>
                <li class="hbar1"><a href="/myapp/products/">Available Products</a></li>
                <li class="hbar1"><a href="/myapp/about/">Find out about this site</a></li>
                <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>
            </ul>
        </div>
    </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h1>Category: {{ category }}</h1>
    <h2>Warehouse Location: {{ warehouse }}</h2>
    <h3>Product List: </h3>
    <ol>
        {% for product in product_list %}
            <li>
                {{ product }}
            </li>
        {% endfor %}
    </ol>
{#    <p><a href="{% url 'myapp:index' %}">Index Page</a></p>#}
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>
    <h1>Category: {{ category }}</h1>
    <h2>Warehouse Location: {{ warehouse }}</h2>
    <h3>Product List: </h3>
    <ol>
        {% for product in product_list %}
            <li>
                {{ product }}
            </li>
        {% endfor %}
    </ol>
    <p><a href="{% url 'myapp:index' %}">Index Page</a></p>
</body>
</html>

myapp/templates/myapp/display_profile_images.html
{% extends 'myapp/base.html' %}
{% block body_block %}
			<div class="col-md-4">
					<img src="{{ profile_images.photo.url }}" class="img-responsive" style="width: 30%; float: left; margin-right: 10px;" />
			</div>
{#    <p><a href="{% url 'myapp:about' %}">About Page</a></p>#}
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{#{% block myhdg %}Hello {{ username }} {% endblock %}#}
{% block body_block %}
    <p>{{ msg }}</p>
    <p>{{ last_login }}</p>
    {% if request.user.client.photo %}
        <div>
            <img src="{{ request.user.client.photo.url }}" height="200" />
        </div>
    {% endif %}
    {% if user.is_authenticated %}
{#        <a href="{% url 'myapp:upload_photo' %}">upload photo</a>#}
    {% endif %}
{#    {% if user.is_authenticated %}#}
{#        <form action="" method="post" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <input type="submit" value="upload photo" />#}
{#        </form>#}
{#    {% endif %}#}
    {% if cat_list %}
        <h2>List of Categories</h2>
        <ol>
            {% for cat in cat_list %}
                <li>
                    <a href="{% url 'myapp:cat_no' cat.id %}">{{ cat.name}}</a>
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
{#    <p><a href="{% url 'myapp:about' %}">About Page</a></p>#}
{% endblock %}

myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block myhdg %}Hello {{ username }} {% endblock %}
{% block body_block %}

{#    <p>{{ order_product }}</p>#}
    {% for order_product in order_product %}

            <p>{{ order_product.product }}</p>

    {% endfor %}


{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h3>{{ msg }}</h3>

{% endblock %}

myapp/templates/myapp/password_reset.html
<h3>Password Reset</h3>


<form action=" " method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Send Email" />
</form>

myapp/templates/myapp/password_reset_sent.html
<h3>Password reset sent</h3>
<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block myhdg %}You can place an order here {% endblock %}
{% block body_block %}
    <h3>Products</h3>
    {% for prodlist in prodlist %}
        <li>{{ prodlist }}</li>
    {% endfor %}

    <form action="." method="post">
        {% csrf_token %}
{#        https://docs.djangoproject.com/en/3.2/ref/csrf/#}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

myapp/templates/myapp/products.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h3>Available Products</h3>
    <p>
        {% for prod in prodlist %}
            {% if prod.available == True %}
{#                <li>{{ prod }}</li>#}
                <li>
                    <a href="{% url 'myapp:prod_id' prod.id %}">{{ prod.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    </p>
    <p><a href="{% url 'myapp:place_order' %}">Place Order</a></p>
{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_filters %}

{% block body_block %}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Register</button>#}
{#     </form>#}
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Register</button>
    </form>

{#  <div class="container" style="background-color:#f1f1f1">#}
{#    <button type="button" class="cancelbtn">Cancel</button>#}
{#    <span class="psw">Forgot <a href="#">password?</a></span>#}
{#  </div>#}

{% endblock %}